In [1]:
#in the name of god

In [8]:
import pandas as pd
import pickle

In [9]:
df=pd.read_csv('Data\\DF.csv').set_index("timestamp")
with open("Data\\Model_param.txt", "rb") as fp:
        Model_param = pickle.load(fp)

FileNotFoundError: [Errno 2] No such file or directory: 'Model_param.txt'

In [7]:
df

,trip_id,latitude,longitude,altitude,gyr_x,gyr_y,gyr_z,acc_x,acc_y,acc_z
timestamp,,,,,,,,,,
2017-01-19 16:19:04.742113,3,4703.7815,1527.4713,359.9,1.11304,1.53043,-0.90435,0.34766,0.01172,0.96094
2017-01-19 16:19:05.741890,3,4703.7815,1527.4714,359.9,1.11304,1.80870,-0.76522,0.34375,0.01172,0.96484
2017-01-19 16:19:06.738842,3,4703.7816,1527.4716,360.3,1.11304,1.80870,-0.76522,0.33984,0.01172,0.96094
2017-01-19 16:19:07.744001,3,4703.7814,1527.4718,360.5,1.25217,1.73913,-0.90435,0.34375,0.01172,0.95703
2017-01-19 16:19:08.746266,3,4703.7814,1527.4720,360.8,1.32174,1.87826,-0.76522,0.34766,0.00781,0.96875
...,...,...,...,...,...,...,...,...,...,...
2017-01-30 06:58:36.495375,35,4703.5440,1527.7215,358.7,3.33913,6.74783,-0.34783,0.23047,0.11719,0.94531
2017-01-30 06:58:36.692035,35,4703.5440,1527.7215,358.7,3.40870,6.60870,0.06957,0.23828,0.10547,0.94922
2017-01-30 06:58:36.892624,35,4703.5440,1527.7215,358.7,3.20000,6.60870,0.06957,0.23438,0.11328,0.94531
2017-01-30 06:58:37.093979,35,4703.5440,1527.7215,358.7,3.20000,6.81739,0.06957,0.23438,0.10547,0.95313
2017-01-30 06:58:37.297740,35,4703.5440,1527.7215,358.7,2.92174,6.46957,-0.34783,0.23438,0.10547,0.93750